---
apiVersion: v1
kind: Namespace
metadata:
  name: sampleapp
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-01
  namespace: sampleapp
  annotations:
    alb.networking.azure.io/alb-id: /subscriptions/04109105-f3ca-44ac-a3a7-66b4936112c3/resourceGroups/devopsjourneymay2024-rg/providers/Microsoft.ServiceNetworking/trafficControllers/devopsjourneymay2024-alb
spec:
  gatewayClassName: azure-alb-external
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
  addresses:
  - type: alb.networking.azure.io/alb-frontend
    value: alb-frontend
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sampleapp-route
  namespace: sampleapp
spec:
  parentRefs:
  - name: gateway-01
  rules:
  - backendRefs:
    - name: aspnetcore
      port: 80